name: noted
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.19.3 <3.0.0"

dependencies:
    
    dartz: ^0.10.1
    dio: ^5.1.1
    flutter:
        sdk: flutter
    flutter_bloc: ^8.1.2
    flutter_localizations:
        sdk: flutter
    get_it: ^7.6.0
    google_fonts: ^4.0.3
    
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    intl: ^0.18.0
    provider: ^6.0.5
    supabase_flutter: ^1.7.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0
    build_runner: ^2.4.4
    hive_generator: ^2.0.0

flutter:
    uses-material-design: true

    # Enable generation of localized Strings from arb files.
    generate: true

    assets:
        # Add assets from the images directory to the application.
        - assets/images/
