// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUH2x1_muAaYo6PXJ0OWylo3iXFJK_wYs',
    appId: '1:665772173646:web:7f4327902fbdf573b0961f',
    messagingSenderId: '665772173646',
    projectId: 'noted-63886',
    authDomain: 'noted-63886.firebaseapp.com',
    databaseURL: 'https://noted-63886-default-rtdb.firebaseio.com',
    storageBucket: 'noted-63886.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfjOKpHrshYmsFcNBOCD0nKm2Go1ImiQU',
    appId: '1:665772173646:android:ab92e9badf343ce1b0961f',
    messagingSenderId: '665772173646',
    projectId: 'noted-63886',
    databaseURL: 'https://noted-63886-default-rtdb.firebaseio.com',
    storageBucket: 'noted-63886.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4S7Agso5cc5hho250if2HP23HfWLjn70',
    appId: '1:665772173646:ios:9d2d6ac4af3ac58cb0961f',
    messagingSenderId: '665772173646',
    projectId: 'noted-63886',
    databaseURL: 'https://noted-63886-default-rtdb.firebaseio.com',
    storageBucket: 'noted-63886.appspot.com',
    iosClientId: '665772173646-n0df7c04fv0okestcl4s6q90kjt6elf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.noted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4S7Agso5cc5hho250if2HP23HfWLjn70',
    appId: '1:665772173646:ios:9d2d6ac4af3ac58cb0961f',
    messagingSenderId: '665772173646',
    projectId: 'noted-63886',
    databaseURL: 'https://noted-63886-default-rtdb.firebaseio.com',
    storageBucket: 'noted-63886.appspot.com',
    iosClientId: '665772173646-n0df7c04fv0okestcl4s6q90kjt6elf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.noted',
  );
}
